input {
  file {
    path => "/var/log/app/debug.log"
    start_position => "beginning"
    codec => json
  }

  file {
    path => "/var/log/app/error.log"
    start_position => "beginning"
    codec => json
  }
}

filter {
  mutate {
    add_field => { "log_type" => "django_loguru" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
