# Generated by Django 4.2.15 on 2025-11-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcionConvocatoria", models.CharField(max_length=512)),
                (
                    "tipoConvocatoria",
                    models.CharField(
                        choices=[("interna", "Interna"), ("externa", "Externa")],
                        max_length=64,
                    ),
                ),
                ("fechaPublicacion", models.DateTimeField()),
                ("fechaCierre", models.DateTimeField()),
                ("fechaAsignacionTema", models.DateTimeField()),
                ("fechaClaseMagistral", models.DateTimeField()),
                (
                    "estadoConvocatoria",
                    models.CharField(
                        choices=[
                            ("publicado", "Publicado"),
                            ("en_proceso", "En proceso"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "convocatoria",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCurso", models.CharField(max_length=64)),
                ("codigoCurso", models.CharField(max_length=20)),
                ("creditosCurso", models.IntegerField()),
                (
                    "facultad",
                    models.CharField(
                        choices=[
                            ("faua", "Facultad de Arquitectura, Urbanismo y Artes"),
                            ("fic", "Facultad de Ingeniería Civil"),
                            (
                                "fieecs",
                                "Facultad de Ingeniería Económica, Estadística y Ciencias Sociales",
                            ),
                            (
                                "figmm",
                                "Facultad de Ingeniería Geológica, Minera y Metalúrgica",
                            ),
                            ("fiee", "Facultad de Ingeniería Eléctrica y Electrónica"),
                            ("fim", "Facultad de Ingeniería Mecánica"),
                            ("fc", "Facultad de Ciencias"),
                            (
                                "fipp",
                                "Facultad de Ingeniería de Petróleo, Gas Natural y Petroquímica",
                            ),
                            ("fiqt", "Facultad de Ingeniería Química y Textil"),
                            ("fia", "Facultad de Ingeniería Ambiental"),
                            ("fiis", "Facultad de Ingeniería Industrial y de Sistemas"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "curso",
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estadoDocente",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "docente",
            },
        ),
        migrations.CreateModel(
            name="Evaluador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipoEvaluador",
                    models.CharField(
                        choices=[("alumno", "Alumno"), ("docente", "Docente")],
                        max_length=64,
                    ),
                ),
                (
                    "estadoEvaluador",
                    models.CharField(
                        choices=[
                            ("convocado", "Convocado"),
                            ("confirmado", "Confirmado"),
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "evaluador",
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("apellidoPaterno", models.CharField(max_length=128)),
                ("apellidoMaterno", models.CharField(max_length=128)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("correo", models.EmailField(max_length=64)),
                ("telefono", models.CharField(max_length=9)),
                (
                    "genero",
                    models.CharField(
                        choices=[("masculino", "Masculino"), ("femenino", "Femenino")],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "persona",
            },
        ),
        migrations.CreateModel(
            name="Plaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estadoPlaza",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=64,
                    ),
                ),
                (
                    "tipoPlaza",
                    models.CharField(
                        choices=[
                            ("laboratorio", "Laboratorio"),
                            ("practica", "Practica"),
                            ("teoria", "Teoria"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.convocatoria",
                    ),
                ),
            ],
            options={
                "db_table": "plaza",
            },
        ),
        migrations.CreateModel(
            name="Silabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoSilabus", models.CharField(max_length=20)),
                ("sistemaEvaluacion", models.CharField(max_length=32)),
                ("fechaSilabus", models.DateField()),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.curso"
                    ),
                ),
            ],
            options={
                "db_table": "silabus",
            },
        ),
        migrations.CreateModel(
            name="Temas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoTema", models.CharField(max_length=20)),
                ("nombreTema", models.CharField(max_length=32)),
                ("duracionTema", models.IntegerField()),
                (
                    "silabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.silabus"
                    ),
                ),
            ],
            options={
                "db_table": "temas",
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoSeccion", models.CharField(max_length=20)),
                (
                    "estadoSeccion",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=20,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.curso"
                    ),
                ),
            ],
            options={
                "db_table": "seccion",
            },
        ),
        migrations.CreateModel(
            name="Requisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=128)),
                ("vigencia", models.CharField(max_length=64)),
                (
                    "plaza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.plaza"
                    ),
                ),
            ],
            options={
                "db_table": "requisito",
            },
        ),
        migrations.CreateModel(
            name="Postulante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estadoPostulante",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("aceptado", "Aceptado"),
                            ("calificado", "Calificado"),
                            ("aprobado", "Desaprobado"),
                            ("desaprobado", "Desaprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.convocatoria",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.persona"
                    ),
                ),
            ],
            options={
                "db_table": "postulante",
            },
        ),
        migrations.AddField(
            model_name="plaza",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.seccion"
            ),
        ),
        migrations.CreateModel(
            name="NotaPostulante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notaClaseCriterio1", models.IntegerField(default=0)),
                ("notaClaseCriterio2", models.IntegerField(default=0)),
                ("notaClaseCriterio3", models.IntegerField(default=0)),
                ("notaClaseCriterio4", models.IntegerField(default=0)),
                ("notaDocumentoCriterio1", models.IntegerField()),
                ("notaDocumentoCriterio2", models.IntegerField()),
                ("notaDocumentoCriterio3", models.IntegerField()),
                ("notaDocumentoCriterio4", models.IntegerField()),
                ("notaDocumentoCriterio5", models.IntegerField()),
                ("notaDocumentoCriterio6", models.IntegerField()),
                (
                    "estadoNotaPostulante",
                    models.CharField(
                        choices=[
                            ("por_calificar", "Por Calificar"),
                            ("revisado_parcialmente", "Revisado Parcialmente"),
                            ("completo", "Completo"),
                        ],
                        default="por_calificar",
                        max_length=64,
                    ),
                ),
                (
                    "evaluador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.evaluador",
                    ),
                ),
                (
                    "postulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.postulante",
                    ),
                ),
            ],
            options={
                "db_table": "nota_postulante",
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=15,
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.seccion"
                    ),
                ),
            ],
            options={
                "db_table": "horario",
            },
        ),
        migrations.AddField(
            model_name="evaluador",
            name="persona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.persona",
            ),
        ),
        migrations.CreateModel(
            name="EvaluacionDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notaEvaluacion", models.FloatField(blank=True, null=True)),
                ("cicloAcademico", models.CharField(max_length=10)),
                ("cantidadAlumnos", models.CharField(max_length=64)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.docente"
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.seccion"
                    ),
                ),
            ],
            options={
                "db_table": "evaluacion_docente",
            },
        ),
        migrations.CreateModel(
            name="EncargadoConsejo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estadoEncargadoConsejo",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=64,
                    ),
                ),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.persona"
                    ),
                ),
            ],
            options={
                "db_table": "encargado_consejo",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoDocumento", models.CharField(max_length=64)),
                ("archivo", models.BinaryField(editable=True)),
                ("fechaRecepcion", models.DateField()),
                (
                    "estadoDocumento",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("en_revision", "En revisión"),
                            ("rechazado", "Rechazado"),
                            ("aceptado", "Aceptado"),
                            ("calificado", "Calificado"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "postulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.postulante",
                    ),
                ),
            ],
            options={
                "db_table": "documento",
            },
        ),
        migrations.AddField(
            model_name="docente",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.persona"
            ),
        ),
        migrations.CreateModel(
            name="Decano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estadoDecano",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=64,
                    ),
                ),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.persona"
                    ),
                ),
            ],
            options={
                "db_table": "decano",
            },
        ),
        migrations.CreateModel(
            name="ClaseMagistral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaProgramacion", models.DateField()),
                ("horaProgramada", models.TimeField()),
                ("temaAsignado", models.CharField(max_length=64)),
                (
                    "estadoClaseMagistral",
                    models.CharField(
                        choices=[
                            ("solicitado", "Solicitado"),
                            ("programado", "Programado"),
                            ("iniciada", "Iniciada"),
                            ("en_proceso", "En proceso"),
                            ("calificado", "Calificado"),
                            ("finalizado", "Finalizado"),
                            ("documentado", "Documentado"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "postulante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.postulante",
                    ),
                ),
            ],
            options={
                "db_table": "clase_magistral",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("codigoUsuario", models.CharField(max_length=64, unique=True)),
                ("nombreUsuario", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "facultad",
                    models.CharField(
                        choices=[
                            ("faua", "Facultad de Arquitectura, Urbanismo y Artes"),
                            ("fic", "Facultad de Ingeniería Civil"),
                            (
                                "fieecs",
                                "Facultad de Ingeniería Económica, Estadística y Ciencias Sociales",
                            ),
                            (
                                "figmm",
                                "Facultad de Ingeniería Geológica, Minera y Metalúrgica",
                            ),
                            ("fiee", "Facultad de Ingeniería Eléctrica y Electrónica"),
                            ("fim", "Facultad de Ingeniería Mecánica"),
                            ("fc", "Facultad de Ciencias"),
                            (
                                "fipp",
                                "Facultad de Ingeniería de Petróleo, Gas Natural y Petroquímica",
                            ),
                            ("fiqt", "Facultad de Ingeniería Química y Textil"),
                            ("fia", "Facultad de Ingeniería Ambiental"),
                            ("fiis", "Facultad de Ingeniería Industrial y de Sistemas"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.persona"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
        ),
    ]
